# Generated by Django 4.1.2 on 2022-10-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(model_name="board", old_name="idx", new_name="id",),
    ]
